### CNN

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# 패딩 : 경계값 처리
# tf.pad(tensor,paddings,mode='constant',constant_values=0,name=None)

#1 . 1D input
A = np.array([1,2,3,4,5]).astype('float32')

#2 . 
p=2
paddings = np.array([[p,p]])

#3 . 
B = tf.pad(A,paddings,"constant")
# [0. 0. 1. 2. 3. 4. 5. 0. 0.]
C = tf.pad(A,paddings,"reflect")
# [3. 2. 1. 2. 3. 4. 5. 4. 3.]
D = tf.pad(A,paddings,"symmetric")
# [2. 1. 1. 2. 3. 4. 5. 5. 4.]

print(B.numpy())
print(C.numpy())
print(D.numpy())



[0. 0. 1. 2. 3. 4. 5. 0. 0.]
[3. 2. 1. 2. 3. 4. 5. 4. 3.]
[2. 1. 1. 2. 3. 4. 5. 5. 4.]


In [ ]:
import tensorflow as tf
import numpy as np

def pad1d_infor(steps,kernel_size=2,strides=1,
                dilation_rate=1,padding='valid'):
  k = (kernel_size-1)*dilation_rate + 1
  if padding == 'valid':
    new_steps = int(np.ceil((steps-k+1)/strides))
    pad_left,pad_right = (0,0)
    
  

### 1차원 풀링 (268P)

풀링 : 2개 이상 것 공유 or 조합
CNN의 풀링 : 여러 값을 하나로 다운 샘플링
- 훈련 파라미터 없음.

1차원 폴링

In [15]:
#1차원 최대풀링 ## padding = "valid"
import tensorflow as tf
import numpy as np

#1. GPU 메모리 부족에 대비.
# gpus = tf.config.experimental.list_physical_devices('GPU')
# # tf.config.experimental.set_memory_growth(gpus[0],True)
# print(type(gpus))
# print(gpus)

#2. 1D input
A = np.array([1,2,3,4,5]).astype('float32')

#3. cal output size
k = 2
s = 2
n = len(A)
output_size = int(np.ceil((n-k+1)/s))
print(output_size)

#4. build model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(5,1)))
model.add(tf.keras.layers.MaxPool1D())
model.summary()

A = np.reshape(A,(1,5,1))
output = model.predict(A)
B = output.flatten()
print(B)

2
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 max_pooling1d (MaxPooling1D  (None, 2, 1)             0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 174ms/step
[2. 4.]


In [16]:
## 1차원 최대풀링 padding = "same"
import tensorflow as tf
import numpy as np

# 1.create 1D input
A = np.array([1,2,3,4,5]).astype('float32')

# 2.calculate padding and output size
k = 2
s = 2
n = len(A)

##
new_steps = int(np.ceil(n/s))
print(new_steps)

##
pad_width = max((new_steps - 1)* s + k - n,0)
pad_left = pad_width
pad_right = pad_width - pad_left

paddings = np.array([pad_left,pad_right])
B = tf.pad(A,paddings,"symmetric")

# 3.as_integer_ratio
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(5,1)))
model.add(tf.keras.layers.MaxPool1D(pool_size=k,strides=s,padding="same"))