In [22]:
enable_eager_execution()

ValueError: tf.enable_eager_execution must be called at program startup.

# 1장

## 인공지능, 딥러닝
- 인공지능 기본 키워드
```
자연어처리(음성인식)
인공신경만
퍼지로직
로보틱스
컴퓨터 비전
패턴인식
기계학습
딥러닝
```

- 기계학습
: 인간과 같이 학습할 수 있도록.

- 딥러닝
: 층을 쌓아 학습하는 기계학습 분야.

## 감독학습, 무감독학습, 강화학습
- 감독학습
: 정답 레이블 있는 데이터 셋 사용.
=> 입력에 대해 기대되는 목표값 사용. 오차 최소화.
ex) 물체 인식, 분류 등에 사용.

- 무감독학습
: 레이블 없는 데이터셋 사용. 유사한 특징 가지는 데이터의 분포, 군집, 분할 등을 계산.
ex) k-mean 클러스터링 알고리즘.

- 강화학습
: 환경과 상호작용 하면서, 누적 보상을 최대화하기 위한 상태에서 최적의 행동인 정책 학습.


## 텐서플로우 설치

1. 텐서플로우 CPU 버전 
```
pip install tensorflow-cpu
```
* cpu 버전은 CUDA toolkit, cuDNN 설치 x
  - CUDA : 그래픽
  - cuDNN : 딥러닝 가속 라이브러리

2. 기타 관련 패키지 설치
```
pip -m install --upgrade pip
pip install tensorflow
pip install pilow
pip install opencv-python
pip install matplotlib
```

3. 환경변수 설정
```
변수 이름 : CUDA_PATH_V10_1
변수 값 : C:\Program Files\NVDIA GPU Computing Toolkit\CUDA\v10.1
```
* XLA_CPU, XLA_GPU : CUDA 커널 지원하기 위한 가속선형대수 최적화 컴파일러

* GPU 할당 관련
=> 코랩에서 실행 시 오류 없으니, PC 환경에 따라 GPU 할당 문제 생길 수 있음.
=> 해결방법
```
# 1. 메모리 확장 설정
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0],True)

# 2. 메모리 제한 설정
gpus = tf.config.experimental.list_physical_device('GPU')
tf.config.experimental.set_virtual_device_configuration(
  gpus[0],
  [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)]
)
```
  1. 메모리 확장 설정
  : tf.config.experimental.set_memory_growth()
  ==> 메모리 증가를 허용. 초기에는 GPU 조금만 할당
  ==> 더 많이 필요할떄 tf에 할당된 GPU영역을 확장.

  2. tf.config.experimental.set_virtual_device_configuration()
  ==> GPU로 메모리 사용 제한.

In [ ]:
pip install tensorflow

# 2장. 텐서플로 기초

## 2.1 즉시 실행모드와 텐서 생성.
즉시실행 모드 활성화 => tf.Session() 생성 않고도 실행 가능.

즉시실행모드 관련

In [1]:
import tensorflow as tf
from tensorflow.python.framework.ops import disable_eager_execution
tf.executing_eagerly()  # True : 즉시 실행모드 활성화 되어있음.

# disable_eager_execution() # 즉시실행모드 비활성화 메소드
tf.executing_eagerly()  # False : 즉시 실행모드 비활성화 되어있음.

True

### 텐서 생성 (tf.constant)

In [2]:
# 1 Graph construction
a = tf.constant(1)  # 정수형 텐서 생성 (값 할당 x)
b = tf.constant(2)  # 정수형 텐서 생성 (값 할당 x)
c = a + b           # 계산 그래프 생성
print(a)
print(b)
print(c)
"""
Tensor("Const_2:0", shape=(), dtype=int32)
:
Tensor("Const_3:0", shape=(), dtype=int32)
Tensor("add_1:0", shape=(), dtype=int32)
"""

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


'\nTensor("Const_2:0", shape=(), dtype=int32)\n:\nTensor("Const_3:0", shape=(), dtype=int32)\nTensor("add_1:0", shape=(), dtype=int32)\n'

In [ ]:
# 2 Graph execution
sess = tf.compat.v1.Session()
sess.run(a)
sess.run(b)
sess.run(c)
## 세션 만들어서 실행 => 텐서 값 반환
sess.close()


In [5]:
a = tf.constant(1)  # 정수형 텐서 생성 (값 할당 x)
b = tf.constant(2)  # 정수형 텐서 생성 (값 할당 x)
c = a + b           # 계산 그래프 생성

a.numpy(),b.numpy(),c.numpy()   # (1, 2, 3) => numpy 영역에 값이 있음을 알 수 있음.

(1, 2, 3)

In [16]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant([1,2,3,4])
c = tf.constant([[1,2],[3,4]])
d = tf.constant([[[1,2],[3,4]]])

a   # <tf.Tensor: shape=(), dtype=int32, numpy=1>
b   # <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>
c
# <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
# array([[1, 2],
#        [3, 4]])>
d
# <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
# array([[[1, 2],
#         [3, 4]]])>

## 타입만 보고싶을땐?
a.dtype     # tf.int32

## 차원 보고싶을땐?
a.ndim, b.ndim, c.ndim, d.ndim    # (0, 1, 2, 3)

## 인덱싱, 슬라이싱 되나?
b[0]
b[:2]
c[0,0]
c[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

### 텐서생성 (tf.Variable)

In [23]:
import tensorflow as tf
a = tf.Variable(1)
b = tf.Variable([1,2,3,4])
c = tf.Variable([[1,2],[3,4]])
d = tf.Variable([[[1,2],[3,4]]])

a.dtype   # tf.int32
## tf.Variable로 생성해도 dtype 은 같음.

a.shape, b.shape,c.shape,d.shape
# (TensorShape([]),
#  TensorShape([4]),
#  TensorShape([2, 2]),
#  TensorShape([1, 2, 2]))

a #<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
a.trainable   # True : tf.Variable로 생성한 변수는 훈련가능함.

## 인덱싱, 슬라이싱은 constant 랑 동일하게 다 된다.

True

### tf.zeros(),tf.ones(),tf.zeros_like(),tf.ones_like()

In [31]:
import tensorflow as tf
a = tf.zeros(shape=(2,3))
a
# <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
# array([[0., 0., 0.],
#        [0., 0., 0.]], dtype=float32)>
## default dtype = float32

b = tf.ones(shape=(2,3))
b
# <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
# array([[1., 1., 1.],
#        [1., 1., 1.]], dtype=float32)>

c = tf.zeros_like(b)
c
# <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
# array([[0., 0., 0.],
#        [0., 0., 0.]], dtype=float32)>

d = tf.ones_like(c)
d
# <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
# array([[1., 1., 1.],
#        [1., 1., 1.]], dtype=float32)>

w = tf.Variable(d)
w
# <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
# array([[1., 1., 1.],
#        [1., 1., 1.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### tf.fill(),tf.linspace(), tf.range(),tf.ones_lie()

In [41]:
import tensorflow as tf
a = tf.fill([2,3],2) ## [2,3] 크기에 2를 채움,
a
# <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
# array([[2, 2, 2],
#        [2, 2, 2]])>

b = tf.linspace(0.0,1.0,5)
b
# <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)>
# 0.0~1.0까지 0.5개 만듬(등간격)

c = tf.range(5) 
c
# <tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

d = tf.range(1,5,0.5)
d
# <tf.Tensor: shape=(8,), dtype=float32, numpy=array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float32)>
## 1~5까지 0.5씩. (5 미포함)

w = tf.Variable(d)
## 텐서d로 초기화된 1차원 텐서 변수 w 생성.
w
# <tf.Variable 'Variable:0' shape=(8,) dtype=float32, numpy=array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float32)>

<tf.Variable 'Variable:0' shape=(8,) dtype=float32, numpy=array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float32)>

### tf.reshape(), tf.transpose()

In [48]:
import tensorflow as tf
a = tf.range(6)
a
# <tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>
b = tf.reshape(a,shape=(2,3))
b
# <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
# array([[0, 1, 2],
#        [3, 4, 5]])>
c = tf.reshape(b,shape=(-1,))
c
# <tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

d = tf.transpose(b)
d
# <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
# array([[0, 3],
#        [1, 4],
#        [2, 5]])>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 3],
       [1, 4],
       [2, 5]])>

### tf.concat(), tf.stack()

In [ ]:
import tensorflow as tf
a = tf.constant([1,2])
b = tf.constant([3,4])
c = tf.concat([a,b],axis=0)

tf.stack([a,b]) ## 걍 두개 연결 [[1,2],[3,4]]
tf.stack([a,b],axis=1) ## 이거 사실 디폴트임. 위에꺼랑 결과 같음.
tf.concat([a,b],axis=0) ## 같은 축에 연결함. [1,2,3,4]
# <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

tf.concat([c,b],axis=0)
# <tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 3, 4])>

b = tf.reshape(b,shape=(2,1))
b
# <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
# array([[3],
      #  [4]])>
      
tf.concat([c,b],axis=1) ### 옆으로 붙임.

### concat : axis = 0 => 아래로 붙임
###          axis = 1 => 옆으로 붙임.

### tf.expand()_dims(), tf.squeeze()

In [61]:
import tensorflow as tf
a = tf.constant([1,2])
a

b = tf.expand_dims(a,axis=0)      # 한 차원 확장. (그냥 괄호 씌움)
b

c = tf.expand_dims(a,axis=1)      # 한 차원 확장. (a의 요소들을 쪼개서, 걔들을 각각 원소로 가지는 차원으로 확장)
c

d = tf.expand_dims(c,axis=0)
d

e = tf.squeeze(d)
e  
# <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

f = tf.squeeze(d,axis=2) ### 2번째 축 삭제
f

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

### tf.random

In [70]:
import tensorflow as tf
tf.random.set_seed(1) # 난수 값 초기화
a = tf.range(5)

tf.random.shuffle(a)
tf.random.uniform(shape=(2,3),minval=0,maxval=1)
### 0~1사이 균등분포 초기화

tf.random.normal(shape=(2,3))
### mean = 0, stddev = 1짜리

tf.random.normal(shape=(2,3),mean=10,stddev=2)

tf.random.truncated_normal(shape=(2,3))
# 난수로 초기화된 (2,3)크기

w = tf.Variable(tf.random.truncated_normal(shape=(2,3)))
w

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-1.1771783 , -0.90325946,  0.8419609 ],
       [-0.06870949,  0.33911815, -0.9542566 ]], dtype=float32)>

### 텐서플로 사칙연산

In [72]:
import tensorflow as tf

a = tf.constant([1,2])
## 기본 연산들 :: a의 모든 인자들에 대해 연산을 수행
a+1 #[2,3]
a-1 #[0,1]
a*2
a/2

b = tf.constant([3,4])
a+b
a-b
a*b
a/b

a = tf.constant([[1,2],[3,4]])
b = tf.constant([1,2])
a+b ## tf.add(a,b)
a-b ## tf.subtract(a,b) ## [[0,0],[2,2]]
a*b
a/b

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 1.],
       [3., 2.]])>

### min,max,sum,prod,mean,argmin,argmax,sort

In [79]:
import tensorflow as tf
a = tf.reshape(tf.range(12),shape=(3,4))

print(tf.reduce_min(a)) ## [0, 4, 8] ## default :: axis=1
print(tf.reduce_min(a,axis=0))
print(tf.reduce_min(a,axis=1))

## 똑같은 내용에서 최대값 계산.
print(tf.reduce_max(a))
print(tf.reduce_max(a,axis=0))
print(tf.reduce_max(a,axis=1))

print(tf.reduce_sum(a))
print(tf.reduce_sum(a,axis=0))
print(tf.reduce_sum(a,axis=1))

print(tf.reduce_mean(a))
print(tf.reduce_mean(a,axis=0)) ## 아래방향 평균
print(tf.reduce_mean(a,axis=1)) ## 옆방향 평균




tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([0 4 8], shape=(3,), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)
tf.Tensor([ 3  7 11], shape=(3,), dtype=int32)
tf.Tensor(66, shape=(), dtype=int32)
tf.Tensor([12 15 18 21], shape=(4,), dtype=int32)
tf.Tensor([ 6 22 38], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([1 5 9], shape=(3,), dtype=int32)
